=== PavelBakun/web-xmlparser/src/by/epam/bakun/xmlTask/data/banks.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/banks"
        xmlns:tns="http://www.example.com/banks"
        elementFormDefault="qualified">
    <element name="banks">
        <complexType>
            <sequence>
                <element name="bank"
                         type="tns:Bank"
                         minOccurs="1"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="Bank">
        <sequence>
            <element name="name" type="string" />
            <element name="country" type="string" />
            <element name="typesOfDeposit" type="tns:TypesOfDeposit" />
        </sequence>
    </complexType>
    <complexType name="TypesOfDeposit">
        <sequence>
            <element name="typeOfDeposit" type="tns:TypeOfDeposit" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="TypeOfDeposit">
        <sequence>
            <element name="depositors" type="tns:Depositors" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="name" use="optional" default="Demand">
            <simpleType>
                <restriction base="string">
                    <enumeration value="Demand"></enumeration>
                    <enumeration value="Term"></enumeration>
                    <enumeration value="Calculated"></enumeration>
                    <enumeration value="Storage"></enumeration>
                    <enumeration value="Saving"></enumeration>
                    <enumeration value="Metallic"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="Depositors">
        <sequence>
            <element name="depositor" type="tns:Depositor" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Depositor">
        <sequence>
            <element name="account_id" type="tns:Account_id" />
            <element name="amountOnDeposit" type="double" minOccurs="0" maxOccurs="unbounded" default="0" />
            <element name="profitability" type="double" minOccurs="0" maxOccurs="100" default="10" />
            <element name="timeConstraints" type="date" />
        </sequence>
        <attribute name="name" type="string" use="required" />
    </complexType>
    <simpleType name="Account_id">
        <restriction base="string">
            <pattern value="[0-9]{0,6}"/>
        </restriction>
    </simpleType>
</schema>

=== PavelBakun/web-xmlparser/src/by/epam/bakun/xmlTask/data/banks.xml
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.com/banks"
       xsi:schemaLocation="http://www.example.com/banks banks.xsd">
    <bank>
        <name>BelarusBank</name>
        <country>Belarus</country>
        <typesOfDeposit>
            <typeOfDeposit name="Demand">
                <depositors>
                    <depositor name = "Ivanov">
                        <account_id>1</account_id>
                        <amountOnDeposit>100000</amountOnDeposit>
                        <profitability>11</profitability>
                        <timeConstraints>2021-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Petrov">
                        <account_id>2</account_id>
                        <amountOnDeposit>200000</amountOnDeposit>
                        <profitability>11</profitability>
                        <timeConstraints>2022-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Sidorov">
                        <account_id>3</account_id>
                        <amountOnDeposit>300000</amountOnDeposit>
                        <profitability>11</profitability>
                        <timeConstraints>2023-01-01</timeConstraints>
                    </depositor>
                </depositors>
            </typeOfDeposit>
            <typeOfDeposit name="Term">
                <depositors>
                    <depositor name = "Ivanenko">
                        <account_id>4</account_id>
                        <amountOnDeposit>400000</amountOnDeposit>
                        <profitability>12</profitability>
                        <timeConstraints>2024-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Petrenko">
                        <account_id>5</account_id>
                        <amountOnDeposit>500000</amountOnDeposit>
                        <profitability>12</profitability>
                        <timeConstraints>2025-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Sidorenko">
                        <account_id>6</account_id>
                        <amountOnDeposit>600000</amountOnDeposit>
                        <profitability>12</profitability>
                        <timeConstraints>2026-01-01</timeConstraints>
                    </depositor>
                </depositors>
            </typeOfDeposit>
            <typeOfDeposit name="Calculated">
                <depositors>
                    <depositor name = "Ivanchuk">
                        <account_id>7</account_id>
                        <amountOnDeposit>700000</amountOnDeposit>
                        <profitability>13</profitability>
                        <timeConstraints>2027-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Petrochuk">
                        <account_id>8</account_id>
                        <amountOnDeposit>800000</amountOnDeposit>
                        <profitability>13</profitability>
                        <timeConstraints>2028-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Sidorchuk">
                        <account_id>9</account_id>
                        <amountOnDeposit>900000</amountOnDeposit>
                        <profitability>13</profitability>
                        <timeConstraints>2029-01-01</timeConstraints>
                    </depositor>
                </depositors>
            </typeOfDeposit>
            <typeOfDeposit name="Storage">
                <depositors>
                    <depositor name = "Ivanin">
                        <account_id>10</account_id>
                        <amountOnDeposit>1000000</amountOnDeposit>
                        <profitability>14</profitability>
                        <timeConstraints>2030-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Petrin">
                        <account_id>11</account_id>
                        <amountOnDeposit>1100000</amountOnDeposit>
                        <profitability>14</profitability>
                        <timeConstraints>2031-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Sidorin">
                        <account_id>12</account_id>
                        <amountOnDeposit>1200000</amountOnDeposit>
                        <profitability>14</profitability>
                        <timeConstraints>2032-01-01</timeConstraints>
                    </depositor>
                </depositors>
            </typeOfDeposit>
            <typeOfDeposit name="Saving">
                <depositors>
                    <depositor name = "Sergeev">
                        <account_id>13</account_id>
                        <amountOnDeposit>1300000</amountOnDeposit>
                        <profitability>15</profitability>
                        <timeConstraints>2033-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Egorov">
                        <account_id>14</account_id>
                        <amountOnDeposit>1400000</amountOnDeposit>
                        <profitability>15</profitability>
                        <timeConstraints>2034-01-01</timeConstraints>
                    </depositor>
                </depositors>
            </typeOfDeposit>
            <typeOfDeposit name="Metallic">
                <depositors>
                    <depositor name = "Sergeenko">
                        <account_id>15</account_id>
                        <amountOnDeposit>1500000</amountOnDeposit>
                        <profitability>16</profitability>
                        <timeConstraints>2035-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Egorenko">
                        <account_id>16</account_id>
                        <amountOnDeposit>1600000</amountOnDeposit>
                        <profitability>16</profitability>
                        <timeConstraints>2036-01-01</timeConstraints>
                    </depositor>
                </depositors>
            </typeOfDeposit>
        </typesOfDeposit>
    </bank>
    <bank>
        <name>Econom</name>
        <country>Belarus</country>
        <typesOfDeposit>
            <typeOfDeposit name="Demand">
                <depositors>
                    <depositor name = "Ivanov">
                        <account_id>1</account_id>
                        <amountOnDeposit>100000</amountOnDeposit>
                        <profitability>11</profitability>
                        <timeConstraints>2021-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Petrov">
                        <account_id>2</account_id>
                        <amountOnDeposit>200000</amountOnDeposit>
                        <profitability>11</profitability>
                        <timeConstraints>2022-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Sidorov">
                        <account_id>3</account_id>
                        <amountOnDeposit>300000</amountOnDeposit>
                        <profitability>11</profitability>
                        <timeConstraints>2023-01-01</timeConstraints>
                    </depositor>
                </depositors>
            </typeOfDeposit>
            <typeOfDeposit name="Term">
                <depositors>
                    <depositor name = "Ivanenko">
                        <account_id>4</account_id>
                        <amountOnDeposit>400000</amountOnDeposit>
                        <profitability>12</profitability>
                        <timeConstraints>2024-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Petrenko">
                        <account_id>5</account_id>
                        <amountOnDeposit>500000</amountOnDeposit>
                        <profitability>12</profitability>
                        <timeConstraints>2025-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Sidorenko">
                        <account_id>6</account_id>
                        <amountOnDeposit>600000</amountOnDeposit>
                        <profitability>12</profitability>
                        <timeConstraints>2026-01-01</timeConstraints>
                    </depositor>
                </depositors>
            </typeOfDeposit>
            <typeOfDeposit name="Calculated">
                <depositors>
                    <depositor name = "Ivanchuk">
                        <account_id>7</account_id>
                        <amountOnDeposit>700000</amountOnDeposit>
                        <profitability>13</profitability>
                        <timeConstraints>2027-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Petrochuk">
                        <account_id>8</account_id>
                        <amountOnDeposit>800000</amountOnDeposit>
                        <profitability>13</profitability>
                        <timeConstraints>2028-01-01</timeConstraints>
                    </depositor>
                    <depositor name = "Sidorchuk">
                        <account_id>9</account_id>
                        <amountOnDeposit>900000</amountOnDeposit>
                        <profitability>13</profitability>
                        <timeConstraints>2029-01-01</timeConstraints>
                    </depositor>
                </depositors>
            </typeOfDeposit>
            <typeOfDeposit name="Storage">
                <depositors>
                    <depositor name = "Ivanin">
                        <account_id>10</account_id>
